### ISSUE TITLE
Open suggestion list when getting back and click on the associated input

### ISSUE THREAD

**Issue by gbrault** [Pixabay/JavaScript-autoComplete#17]
First congratulation about this very nice and effective piece of code and leting it open to others!
I have it integrated on my on going RLITE project, which goal is to facilitate embedding structured data and report it with text, all into a web site...
I used your code for what I name "Filtre", [see](https://github.com/gbrault/ArrestDB/blob/master/scripts/Filtre.js), arrond line 120 (code will change a bit...) It was very straightforward to integrate!!!
Just one small improvement, could you add an option 'reselect', which would trigger the last suggested item list popup when you click in an input that was used as the last suggestion, choice being 'completed' or not.
Like this, in my use case, the user can select as an exemple, a customer (with the contact name), then select the associated Orders with an other suggestion input, click on a refresh button, which would then go and fetch the corresponding order detail. Then when she/he clicks back on the order suggestion input, she/he has the choice of selecting a new order to select and see it...Much easier than erase and retype the input...
What do you think? 
Thanks a lot again! Very nice job!

**Comment by SimonSteinberger** [comment]
Hi Gilbert, thanks for your kind feedback :+1: 

At the moment, I'M kept quite busy. But you can fork this code and modify it. If it works, we could include your patch to the code base.

**Comment by gbrault** [comment]
Thanks! I'll give a try...
