### ISSUE TITLE
Unspecified error on IE 10

### ISSUE THREAD

**Issue by evandenberg** [Pixabay/JavaScript-autoComplete#2]
Line 57 "that.setAttribute('data-sc', that.sc);" is throwing a Unspecified error in IE10.
As far as I can see this code isn't used anywhere else so removing this line fixes the issue

**Comment by SimonSteinberger** [comment]
Thanks :+1:  The plugin was portwed from jQuery to vanilla JS. This was an unwanted remaining. However, I don't actually see why the error was thrown.
