### ISSUE TITLE
Autocomplete on demo page returns incorrect results

### ISSUE THREAD

**Issue by scf37** [Pixabay/JavaScript-autoComplete#48]
https://goodies.pixabay.com/javascript/auto-complete/demo.html

type "sca"
expected: Scala
actual: 14 results: ActionScript, AppleScript, Asp .....   Scala, Scheme, SQL

**Comment by gomestai** [comment]
It seems OK in my browser maybe it get fixed

**Comment by blokhin** [comment]
What is the browser? Version? OS? Version of library?

**Comment by enomado** [comment]
probably you're looking for this https://github.com/tremby/JavaScript-autoComplete/commit/616f2abb21204f38bb2dd69d7e7f94db77296736

**Comment by scf37** [comment]
I can't reproduce it anymore.

**Comment by enomado** [comment]
Nevertheless, problem is actual.
Steps to reproduce:
1. start typing `sc` to begin request
2. then fast type `a`
you get values from `sc` on key `sca`.

Commit in fork i've mentioned already fixes the problem.
