### ISSUE TITLE
Cannot be found in Bower

### ISSUE THREAD

**Issue by jameshoward** [Pixabay/JavaScript-autoComplete#7]
`bower install javascript-auto-complete` results in Package javascript-auto-complete not found.

I see there's a `bower.json` config but has this module been registered? http://bower.io/docs/creating-packages/

If so, perhaps the lack of semver version tags means it can’t be found.

**Comment by bio** [comment]
`bower install javascript-auto-complete --save` works for me but yeah there are no tags.
Also you can install package using git endpoint: `bower install https://github.com/Pixabay/JavaScript-autoComplete.git --save`

**Comment by SimonSteinberger** [comment]
Version tag created. This should work now.
