### ISSUE TITLE
How to submit the form on enter or mouse click onSelect?

### ISSUE THREAD

**Issue by dcalixto** [Pixabay/JavaScript-autoComplete#70]
After setup the script and show the results we need to click the search post button to complete the action, but i would like to on the suggestion  submit the form without need to select. is that possible with the onSelect callback?

**Comment by enomado** [comment]
I've done it in my fork https://github.com/enomado/JavaScript-autoComplete

You can pass your own onSelect there. But It's fully unmergeable  and unmaintainable. Perhaps there are almost any feature in some of this library fork :)

**Comment by dcalixto** [comment]
@enomado  thank you very much!

**Comment by dcalixto** [comment]
@enomado just one doubt, did you removed the (term, response) ?
so onSelect: function(e, term, item) dis not use the (e, term, item) ?

**Comment by enomado** [comment]
It accepts even more:
`onSelect: function({ event, value, choice, object, method }) `. but i'm not sure it can tun on <es6

**Comment by dcalixto** [comment]
great! thank you @enomado
